# Generated by Django 5.2.6 on 2025-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
