# Generated by Django 5.1.3 on 2025-09-07 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(help_text='Eco-credits required')),
                ('category', models.CharField(choices=[('environmental', 'Environmental'), ('merchandise', 'Merchandise'), ('digital', 'Digital')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name or path (frontend decides rendering)', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(help_text='Eco-credits spent')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rewards.reward')),
            ],
        ),
    ]
