# Generated by Django 5.1.3 on 2025-09-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('github', 'GitHub')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credits_awarded', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_sessions', to='users.profile')),
            ],
        ),
    ]
