# Generated by Django 5.1.3 on 2025-09-07 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingsession',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='codingsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='codingsession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
