# Generated by Django 5.2.6 on 2025-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_remove_codingsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsession',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
