# Generated by Django 5.2.6 on 2025-09-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_codingsession_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingsession',
            name='session_id',
        ),
    ]
