# Generated by Django 5.2.6 on 2025-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='approved_on',
            new_name='verified_on',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
