# Generated by Django 5.2.6 on 2025-09-06 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
