# Generated by Django 5.2.6 on 2025-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_activity_date_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
