# Generated by Django 5.2.6 on 2025-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('VERIFIED', 'verified'), ('REJECTED', 'rejected')], default='PENDING', max_length=12),
        ),
    ]
