# Generated by Django 5.2.6 on 2025-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(
                choices=[
                    ('hiking', 'hiking'),
                    ('walking', 'walking'),
                    ('running', 'running'),
                    ('cycling', 'cycling'),
                    ('climbing', 'climbing'),
                    ('camping', 'camping'),
                    ('gardening', 'gardening'),
                    ('other', 'other')
                ],
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_tmp',
            field=models.TimeField(null=True),
        ),
    ]
