# Generated by Django 5.2.6 on 2025-09-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_activity_alter_activity_duration'),
        ('activities', '0006_alter_activity_status'),
    ]

    operations = [
    ]
