# Generated by Django 5.2.6 on 2025-09-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_merge_20250911_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('hiking', 'hiking'), ('walking', 'walking'), ('running', 'running'), ('cycling', 'cycling'), ('climbing', 'climbing'), ('camping', 'camping'), ('gardening', 'gardening'), ('other', 'other')], max_length=25),
        ),
    ]
