# Generated by Django 5.2.6 on 2025-09-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_activity'),
    ]

    operations = [
        # Drop the old duration field
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='duration_tmp',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
