# Generated by Django 5.2.6 on 2025-09-11 07:53
from django.db import migrations
import datetime

def convert_int_to_time(apps, schema_editor):
    Activity = apps.get_model("activities", "Activity")
    for obj in Activity.objects.all():
        if isinstance(obj.duration, int):
            hours = obj.duration // 60
            minutes = obj.duration % 60
            obj.duration = datetime.time(hour=hours, minute=minutes)
            obj.save(update_fields=["duration"])

class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_remove_activity_duration_tmp_alter_activity_duration"),
    ]

    operations = [
        migrations.RunPython(convert_int_to_time, migrations.RunPython.noop),
    ]
