# Generated by Django 5.2.6 on 2025-09-11 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_convert_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
