# Generated by Django 5.2.6 on 2025-09-15 15:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='verification_proof',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='activities'),
        ),
    ]
